<a href="https://colab.research.google.com/github/istiq5089-ops/TUGAS1/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv("/data_tugas 2.csv")
df.head()

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height
0,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
1,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
2,?,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4
3,164,audi,gas,four,sedan,99.8,176.6,66.2,54.3
4,164,audi,gas,four,sedan,99.4,176.6,66.4,54.3

Menampilkan Jumlah Data Hilang

In [15]:
missing_values = df.isnull().sum()
print(missing_values)

normalized-losses     0
make                  4
bahan-bakar          13
jumlah-pintu         16
body-style           12
wheel-bases           3
length                8
width                 5
height                4
dtype: int64

Mengganti Missing Value pada Variabel Kategori

In [16]:
kategori = ["make","bahan-bakar","jumlah-pintu","body-style"]

for col in kategori:
    df[col].fillna("unknown", inplace=True)

/tmp/ipykernel_2474/2906199275.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna("unknown", inplace=True)

In [17]:
for col in kategori:
    print("Ringkasan kategori pada kolom:", col)
    print(df[col].value_counts())
    print()

Ringkasan kategori pada kolom: make
make
toyota           32
mazda            17
nissan           17
honda            13
mitsubishi       12
volkswagen       12
volvo            11
subaru           11
peugot           11
dodge             9
mercedes-benz     8
bmw               8
plymouth          7
audi              7
saab              6
porsche           4
unknown           4
isuzu             4
alfa-romero       3
chevrolet         3
jaguar            3
renault           2
mercury           1
Name: count, dtype: int64

Ringkasan kategori pada kolom: bahan-bakar
bahan-bakar
gas        173
diesel      19
unknown     13
Name: count, dtype: int64

Ringkasan kategori pada kolom: jumlah-pintu
jumlah-pintu
four       101
two         86
unknown     16
?            2
Name: count, dtype: int64

Ringkasan kategori pada kolom: body-style
body-style
sedan          88
hatchback      67
wagon          24
unknown        12
hardtop         8
convertible     6
Name: count, dtype: int64

Mengganti Missing Value pada Variabel Numerik

In [18]:
numerik = ["length","width","height"]

for col in numerik:
    mean_value = df[col].mean()
    df[col].fillna(mean_value, inplace=True)

/tmp/ipykernel_2474/1443237490.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mean_value, inplace=True)

Min-Max Normalization

In [23]:
df["wheel-bases-normalized"] = (
    (df["wheel-bases"] - df["wheel-bases"].min()) /
    (df["wheel-bases"].max() - df["wheel-bases"].min())
)

In [ ]:
display(df.head())

Z-Score Normalization

In [25]:
for col in numerik:
    df[col + "_zscore"] = (df[col] - df[col].mean()) / df[col].std()

In [26]:
df.head()

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height,wheel-bases-normalized,length_zscore,width_zscore,height_zscore
0,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8,0.058309,-0.428526,-0.867630,-2.038094
1,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8,0.058309,-0.428526,-0.867630,-2.038094
2,?,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4,0.230321,-0.226967,-0.204232,-0.552035
3,164,audi,gas,four,sedan,99.8,176.6,66.2,54.3,0.384840,0.226541,0.127467,0.232274
4,164,audi,gas,four,sedan,99.4,176.6,66.4,54.3,0.373178,0.226541,0.222238,0.232274